version: "3.8"

services:
    admin:
        restart: always
        volumes:
            - .:/app
            - /app/node_modules
        build:
            context: ./
            dockerfile: docker/Dockerfile
        environment:
            - VITE_API_URL=${VITE_API_URL}
        ports:
            - '5173:5173'