version: "3.8"

services:
    admin:
        restart: always
        working_dir: /app
        volumes:
            - /app/node_modules
        build:
            context: ./
            dockerfile: docker/Dockerfile
        develop:
            watch:
                -   action: sync
                    path: ./
                    target: /app
                    ignore:
                        - node_modules/
                -   action: rebuild
                    path: package.json
        environment:
            - VITE_API_URL=${VITE_API_URL}
        ports:
            - '5173:5173'